version: "2"
services: 
    web:
        build:
            context: .
        command: npm start
        volumes: 
            - .:/app
            - /app/node_modules
        ports:
            - 3000:3000 
